// <auto-generated />
namespace IdentityProvider.Repository.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Fixed_a_boo_boo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fixed_a_boo_boo));
        
        string IMigrationMetadata.Id
        {
            get { return "201808231237171_Fixed_a_boo_boo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
