// <auto-generated />
namespace IdentityProvider.Repository.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Further_Changes_Cant_Remember_What : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Further_Changes_Cant_Remember_What));
        
        string IMigrationMetadata.Id
        {
            get { return "201808221022234_Further_Changes_Cant_Remember_What"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
